### ISSUE TITLE
Not able to Share Image on Instagram via RN 0.61.5 & ios 13.3

### ISSUE THREAD

**Issue by mkharibalaji** [r0b0t3d/react-native-social-share#1]
Hi,
    First of all its a wonderful Library that exactly meets my expectations.I think recently Instagram is strictly allowing only the specific URL Schemes in iOS as listed in this,

https://developers.facebook.com/docs/instagram/sharing-to-feed

I tried even locally instagram://library?AssetPath=<File> is not working.
I found it working only via UIDocumentInteractionController or via igo ( com.instagram.exclusivegram) Could you please provide an alternate way within this library to use the sharing via UIDocumentInteractionController as a fallback or a separate method to share.

Thanks

**Comment by r0b0t3d** [comment]
@mkharibalaji 
Currently, I am using this lib for my internal project. So I don't have much time to write document also support new features. So I think we should keep this thread to discuss why sharing not working. You can open another issue for feature request `Document Interaction`. I will check it later.

I am using RN 0.61.5, ios 13.3 and I can still got it working. To share via Instagram, you must save your file to library via `CameraRoll` lib.
```javascript
import CameraRoll from '@react-native-community/cameraroll';

const localFile = "";
const uri = CameraRoll.save(localFile, { type: 'photo' });
```
then use above `uri` to share.

**Comment by mkharibalaji** [comment]
@r0b0t3d - You are correct,I stored the file in Temporary Path and it didn't work using AssetPath URI.It only works with cameraroll.
